---
# This role installs and sets up keepalived

- name: Install keepalived (Centos)
  package: 
    name: keepalived
    state: latest
  tags: keepalived
  notify: restart keepalived

- name: Install check script
  template: 
    src: "{{ keepalived_check_script_name }}.sh.j2 }}"
    dest: "/etc/keepalived/{{ keepalived_check_script_name }}.sh"
    mode: 0755
    owner: root
    group: root
  tags: keepalived
  notify: restart keepalived

- name: Keepalived configuration
  template: 
    src: keepalived.conf.j2 
    dest: /etc/keepalived/keepalived.conf
  tags: keepalived
  notify: restart keepalived

- name: Start keepalived
  service: 
    name: keepalived
    state: started
    enabled: yes
  tags: keepalived
